name = "techwithpaaji"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[build]
command = "npm run deploy"

[build.upload]
format = "service-worker"
